version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    reviewers:
      - "arespawn"
    assignees:
      - "arespawn"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "fix(deps)"
    ignore:
      - dependency-name: "discord.js"
      - dependency-name: "undici"
      - dependency-name: "@discordjs/rest"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "UTC"
    reviewers:
      - "arespawn"
    assignees:
      - "arespawn"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github_actions"
    commit-message:
      prefix: "fix(deps)"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
